BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `unidad` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`nombre`	TEXT NOT NULL UNIQUE,
	`abreviacion`	TEXT NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS `tiendas` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`nombre`	TEXT NOT NULL UNIQUE,
	`horario`	TEXT
);
CREATE TABLE IF NOT EXISTS `recetas` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`nombre`	TEXT NOT NULL,
	`tiempo`	INTEGER,
	`vegano`	INTEGER DEFAULT 0
);
CREATE TABLE IF NOT EXISTS `ingredientes` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`nombre`	TEXT NOT NULL,
	`cantidad`	REAL,
	`precio`	INTEGER,
	`tiendas_id`	INTEGER NOT NULL,
	`unidades_id`	INTEGER NOT NULL,
	FOREIGN KEY(`tiendas_id`) REFERENCES `tiendas`(`id`) ON UPDATE CASCADE ON DELETE CASCADE
);
COMMIT;
