# Generated by Django 3.1.2 on 2021-10-29 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Recetas', '0002_auto_20211029_0016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingrediente',
            name='tienda',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='ingrediente',
        ),
        migrations.CreateModel(
            name='TiendaIngredientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.FloatField()),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recetas.ingrediente')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recetas.tienda')),
            ],
        ),
        migrations.CreateModel(
            name='RecetIngrediente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recetas.ingrediente')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recetas.receta')),
            ],
        ),
    ]
