# Generated by Django 3.2.5 on 2021-11-02 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recetas', '0004_auto_20211029_0523'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='ingredientes',
            field=models.ManyToManyField(through='Recetas.RecetaIngrediente', to='Recetas.Ingrediente'),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='recetaingrediente',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tiendaingrediente',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
