# Generated by Django 3.2.8 on 2021-11-11 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recetas', '0005_auto_20211101_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recetaingrediente',
            name='cantidad',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tiendaingrediente',
            name='precio',
            field=models.FloatField(null=True),
        ),
    ]
