# Generated by Django 3.2.8 on 2021-11-11 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recetas', '0006_auto_20211111_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='descripcion',
            field=models.CharField(max_length=450, null=True),
        ),
    ]
